interface Nota {
  id: string;
  prefijo: string;
  consecutivo: number;
  contrato: string;
  estado: string;
  xml: string;
  enviar: string;
  opciones: string;
  dian: string;
  pagada: string;
  factura: string;
  nit: string; // Nueva propiedad 'nit'
  tipoDeFactura:string;
}

// Generar un tipo de factura aleatorio
const tiposDeFactura = [
  'Facturas',
  'Facturas electronicas',
  'Electronica de contingencia',
  'Facturas anuladas',
  'Electronicas de Habilitacion',
];

const getRandomTipoDeFactura = () =>
  tiposDeFactura[Math.floor(Math.random() * tiposDeFactura.length)];

const initialNotas: Nota[] = [
  {
    id: '1',
    prefijo: 'ABC',
    consecutivo: 123,
    contrato: 'CT-2024-001',
    estado: 'Activo',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Validado',
    pagada: 'Sí',
    factura: 'Factura',
    nit: '1234567890',
    tipoDeFactura: getRandomTipoDeFactura(), // Generar tipo de factura aleatorio
  },
  {
    id: '2',
    prefijo: 'DEF',
    consecutivo: 345,
    contrato: 'CT-2024-002',
    estado: 'Inactivo',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Pendiente',
    pagada: 'No',
    factura: 'Factura',
    nit: '9876543210',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '3',
    prefijo: 'GHI',
    consecutivo: 567,
    contrato: 'CT-2024-003',
    estado: 'Activo',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Validado',
    pagada: 'Sí',
    factura: 'Factura',
    nit: '1122334455',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '4',
    prefijo: 'JKL',
    consecutivo: 789,
    contrato: 'CT-2024-004',
    estado: 'Suspendido',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Pendiente',
    pagada: 'No',
    factura: 'Factura',
    nit: '2233445566',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '5',
    prefijo: 'MNO',
    consecutivo: 1011,
    contrato: 'CT-2024-005',
    estado: 'Activo',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Validado',
    pagada: 'Sí',
    factura: 'Factura',
    nit: '3344556677',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '6',
    prefijo: 'PQR',
    consecutivo: 1233,
    contrato: 'CT-2024-006',
    estado: 'Inactivo',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Pendiente',
    pagada: 'No',
    factura: 'Factura',
    nit: '4455667788',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '7',
    prefijo: 'STU',
    consecutivo: 1455,
    contrato: 'CT-2024-007',
    estado: 'Activo',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Validado',
    pagada: 'Sí',
    factura: 'Factura',
    nit: '5566778899',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '8',
    prefijo: 'VWX',
    consecutivo: 1677,
    contrato: 'CT-2024-008',
    estado: 'Suspendido',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Validado',
    pagada: 'No',
    factura: 'Factura',
    nit: '6677889900',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '9',
    prefijo: 'YZA',
    consecutivo: 1899,
    contrato: 'CT-2024-009',
    estado: 'Inactivo',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Pendiente',
    pagada: 'Sí',
    factura: 'Factura',
    nit: '7788990011',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '10',
    prefijo: 'BCD',
    consecutivo: 2121,
    contrato: 'CT-2024-010',
    estado: 'Activo',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Validado',
    pagada: 'No',
    factura: 'Factura',
    nit: '8899001122',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '11',
    prefijo: 'EFG',
    consecutivo: 2343,
    contrato: 'CT-2024-011',
    estado: 'Suspendido',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Pendiente',
    pagada: 'Sí',
    factura: 'Factura',
    nit: '9900112233',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
  {
    id: '12',
    prefijo: 'HIJ',
    consecutivo: 2565,
    contrato: 'CT-2024-012',
    estado: 'Activo',
    xml: 'Ver',
    enviar: 'Enviar',
    opciones: '...',
    dian: 'Validado',
    pagada: 'No',
    factura: 'Factura',
    nit: '1011122334',
    tipoDeFactura: getRandomTipoDeFactura(),
  },
];

export default initialNotas;
