// src/styles/commonStyles.ts
import { StyleSheet, Platform } from "react-native";
import { COLOR } from "../constants/colors"; // Importa los colores

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLOR.BACKGROUND,
  },
  container: {
    marginTop: 10,
    flex: 1,
    backgroundColor: COLOR.BACKGROUND,
    paddingTop: 0,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLOR.BACKGROUND,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 18,
    color: COLOR.TEXT_MUTED,
    fontFamily: "Lato",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 20,
    paddingTop: Platform.OS === "android" ? 20 : 0,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 5,
  },
  backButtonText: {
    marginLeft: 10,
    fontSize: 18,
    color: COLOR.TEXT_DARK,
    fontFamily: "Lato",
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    fontFamily: "Lato",
    flex: 1,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 18,
    color: COLOR.TEXT_MUTED,
    textAlign: "center",
    marginBottom: 20,
    fontFamily: "Lato",
  },
  categoriesScroll: {
    maxHeight: 60,
    marginBottom: 15,
  },
  categoriesListContent: {
    paddingHorizontal: 20,
    alignItems: "center",
  },
  categoryButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 25,
    backgroundColor: COLOR.CARD_COMPONENT_BG,
    marginHorizontal: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  selectedCategoryButton: {
    backgroundColor: COLOR.ORANGE,
    borderColor: COLOR.ORANGE,
  },
  categoryButtonText: {
    fontSize: 16,
    color: COLOR.TEXT_DARK,
    fontWeight: "bold",
    fontFamily: "Lato",
  },
  selectedCategoryButtonText: {
    color: "#ffffff",
  },
  productsListContent: {
    paddingHorizontal: 10,
  },
  productGridRow: {
    justifyContent: "space-between",
    marginBottom: 10,
  },
  productCard: {
    backgroundColor: COLOR.CARD_COMPONENT_BG,
    borderRadius: 15,
    padding: 10,
    marginHorizontal: 5,
    width: "47%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignItems: "center",
    marginBottom: 10,
  },
  productImage: {
    width: "100%",
    height: 100,
    borderRadius: 10,
    marginBottom: 10,
    resizeMode: "cover",
  },
  productImagePlaceholder: {
    width: "100%",
    height: 100,
    borderRadius: 10,
    marginBottom: 10,
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
  },
  productInfo: {
    width: "100%",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  productName: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    fontFamily: "Lato",
    textAlign: "left",
  },
  productDescription: {
    fontSize: 12,
    color: COLOR.TEXT_MUTED,
    fontFamily: "Lato",
    textAlign: "left",
    marginTop: 2,
  },
  productPrice: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLOR.ORANGE,
    fontFamily: "Lato",
    marginTop: 5,
  },
  addProductButton: {
    backgroundColor: COLOR.ORANGE,
    borderRadius: 20,
    padding: 10,
    position: "absolute",
    bottom: 10,
    right: 10,
    shadowColor: COLOR.ORANGE,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  emptyListContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 50,
    paddingHorizontal: 20,
  },
  emptyListIcon: {
    marginBottom: 20,
  },
  emptyListText: {
    fontSize: 18,
    color: COLOR.TEXT_MUTED,
    textAlign: "center",
    fontFamily: "Lato",
    marginBottom: 10,
  },
  orderSummaryContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLOR.CARD_COMPONENT_BG,
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 8,
  },
  orderSummaryText: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    fontFamily: "Lato",
  },
  reviewOrderButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLOR.ORANGE,
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 20,
    shadowColor: COLOR.ORANGE,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 6,
  },
  reviewOrderButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: "Lato",
  },

  // Estilos del Modal
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  modalContent: {
    backgroundColor: COLOR.BACKGROUND,
    borderRadius: 20,
    padding: 25,
    width: "90%",
    maxHeight: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    marginBottom: 20,
    textAlign: "center",
    fontFamily: "Lato",
  },
  modalCartList: {
    flexGrow: 1,
    paddingBottom: 10,
  },
  cartItemCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLOR.CARD_COMPONENT_BG,
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  cartItemDetails: {
    flex: 2,
  },
  cartItemName: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    fontFamily: "Lato",
  },
  cartItemNotes: {
    fontSize: 12,
    color: COLOR.TEXT_MUTED,
    fontFamily: "Lato",
    marginTop: 2,
    fontStyle: "italic",
  },
  cartItemControls: {
    flexDirection: "row",
    alignItems: "center",
    flex: 3,
    justifyContent: "flex-end",
  },
  quantityButton: {
    backgroundColor: COLOR.ORANGE,
    borderRadius: 5,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 5,
  },
  quantityButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  cartItemQuantity: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    minWidth: 25, // Para que el texto no se mueva mucho
    textAlign: "center",
  },
  cartItemPrice: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLOR.ORANGE,
    marginLeft: 15,
    minWidth: 60, // Para alinear los precios
    textAlign: "right",
  },
  removeCartItemButton: {
    marginLeft: 15,
    padding: 5,
  },
  modalSummary: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 15,
    alignItems: "center",
  },
  modalTotalText: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    marginBottom: 15,
    fontFamily: "Lato",
  },
  submitOrderButton: {
    backgroundColor: COLOR.ORANGE,
    borderRadius: 25,
    paddingVertical: 14,
    paddingHorizontal: 30,
    width: "100%",
    alignItems: "center",
    marginBottom: 10,
    shadowColor: COLOR.ORANGE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
  },
  submitOrderButtonDisabled: {
    backgroundColor: "#f78a59",
    shadowOpacity: 0.2,
    elevation: 3,
  },
  submitOrderButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
    fontFamily: "Lato",
  },
  modalCloseButton: {
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: COLOR.TEXT_MUTED,
    width: "60%",
    alignItems: "center",
  },
  modalCloseButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontFamily: "Lato",
  },
  flatListContent: {
    paddingBottom: 20,
  },
  mesaCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLOR.CARD_COMPONENT_BG,
    borderRadius: 15,
    padding: 15,
    marginVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    width: "100%",
    borderColor: "#e0e0e0",
    borderWidth: 1,
  },
  cardIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#ffe0b2",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  mesaNumber: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    fontFamily: "Lato",
    marginTop: 5,
  },
  cardDetails: {
    flex: 1,
  },
  mesaCapacity: {
    fontSize: 16,
    color: COLOR.TEXT_MUTED,
    fontFamily: "Lato",
    marginBottom: 5,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  statusIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 8,
  },
  mesaStatusText: {
    fontSize: 16,
    color: COLOR.TEXT_DARK,
    fontFamily: "Lato",
  },
  cardArrow: {
    marginLeft: 15,
  },
  emptyListSubText: {
    fontSize: 16,
    color: COLOR.TEXT_MUTED,
    textAlign: "center",
    fontFamily: "Lato",
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLOR.ORANGE,
    borderRadius: 15,
    paddingVertical: 15,
    paddingHorizontal: 30,
    marginTop: 30,
    alignSelf: "center",
    shadowColor: COLOR.ORANGE,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  logoutIcon: {
    marginRight: 10,
  },
  logoutButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
    fontFamily: "Lato",
  },
  pedidoCard: {
    backgroundColor: COLOR.CARD_COMPONENT_BG,
    borderRadius: 15,
    padding: 20,
    marginVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    width: "100%",
    borderColor: "#e0e0e0",
    borderWidth: 1,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    paddingBottom: 10,
  },
  pedidoIdContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  pedidoIdText: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    fontFamily: "Lato",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  statusBadgeText: {
    fontSize: 14,
    fontWeight: "bold",
    fontFamily: "Lato",
  },
  cardBody: {
    marginBottom: 15,
  },
  mesaInfo: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  mesaText: {
    fontSize: 16,
    color: COLOR.TEXT_MUTED,
    fontFamily: "Lato",
  },
  itemsTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLOR.TEXT_DARK,
    marginBottom: 8,
    fontFamily: "Lato",
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  itemQuantity: {
    fontSize: 15,
    fontWeight: "bold",
    color: COLOR.ORANGE,
    marginRight: 8,
    fontFamily: "Lato",
  },
  itemName: {
    fontSize: 15,
    color: COLOR.TEXT_DARK,
    flex: 1,
    fontFamily: "Lato",
  },
  itemNotes: {
    fontSize: 13,
    color: COLOR.TEXT_MUTED,
    fontFamily: "Lato",
    marginLeft: 5,
    fontStyle: "italic",
  },
  noItemsText: {
    fontSize: 14,
    color: COLOR.TEXT_MUTED,
    fontStyle: "italic",
    fontFamily: "Lato",
  },
  actionButton: {
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  actionButtonText: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "bold",
    fontFamily: "Lato",
  },
  textInput: {
    backgroundColor: COLOR.CARD_COMPONENT_BG,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 15,
    fontSize: 16,
    color: COLOR.TEXT_DARK,
    fontFamily: "Lato",
    borderWidth: 1,
    borderColor: "#e0e0e0",
    marginBottom: 10,
  },
  secondaryButton: {
    backgroundColor: COLOR.CARD_COMPONENT_BG,
    borderColor: COLOR.ORANGE,
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
});
