export enum RoleName {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  COCINERO = 'COCINERO',
  CAJERO = 'CAJERO',
  MESERO = 'MESERO',
  DOMICILIARIO = 'DOMICILIARIO',
}

export const GLOBAL_ESTABLISHMENT_ID = '00000000-0000-0000-0000-000000000000'; 
export const GLOBAL_ESTABLISHMENT_NAME = 'Sistema Global'; 