export const descripciones = [
  {
    id: "des1",
    descripcion:
      "Recursos financieros, técnicos humanos y de otra índole requeridos para coordinar y desarrollar el Sistema de Gestión de la Seguridad y Salud en el Trabajo (SG-SST)",
    pesoPorcentual: 4,
    seccionID: "sec1",
  },
  {
    id: "des2",
    descripcion:
      "Capacitación en el Sistema de Gestión de la Seguridad y Salud en el Trabajo",
    pesoPorcentual: 6,
    seccionID: "sec1",
  },
  {
    id: "des3",
    descripcion: "Política de Seguridad y Salud en el Trabajo",
    pesoPorcentual: 1,
    seccionID: "sec2",
  },
  {
    id: "des4",
    descripcion: "Objetivos del SG-SST",
    pesoPorcentual: 1,
    seccionID: "sec2",
  },
  {
    id: "des5",
    descripcion: "Evaluación inicial del SG-SST",
    pesoPorcentual: 1,
    seccionID: "sec2",
  },
  {
    id: "des6",
    descripcion: "Plan Anual de Trabajo",
    pesoPorcentual: 2,
    seccionID: "sec2",
  },
  {
    id: "des7",
    descripcion: "Conservación de la documentación",
    pesoPorcentual: 2,
    seccionID: "sec2",
  },
  {
    id: "des8",
    descripcion: "Rendición de cuentas",
    pesoPorcentual: 1,
    seccionID: "sec2",
  },
  {
    id: "des9",
    descripcion: "Normatividad nacional vigente y aplicable en materia de SST",
    pesoPorcentual: 2,
    seccionID: "sec2",
  },
  {
    id: "des10",
    descripcion: "Comunicación",
    pesoPorcentual: 1,
    seccionID: "sec2",
  },
  {
    id: "des11",
    descripcion: "Adquisiciones",
    pesoPorcentual: 1,
    seccionID: "sec2",
  },
  {
    id: "des12",
    descripcion: "Contratación",
    pesoPorcentual: 2,
    seccionID: "sec2",
  },
  {
    id: "des13",
    descripcion: "Gestión del cambio",
    pesoPorcentual: 1,
    seccionID: "sec2",
  },
  {
    id: "des14",
    descripcion: "Condiciones de salud en el trabajo",
    pesoPorcentual: 9,
    seccionID: "sec3",
  },
  {
    id: "des15",
    descripcion:
      "Registro, reporte e investigación de las enfermedades laborales, los incidentes y accidentes del trabajo",
    pesoPorcentual: 5,
    seccionID: "sec3",
  },
  {
    id: "des16",
    descripcion:
      "Mecanismos de vigilancia de las condiciones de salud de los trabajadores",
    pesoPorcentual: 6,
    seccionID: "sec3",
  },
  {
    id: "des17",
    descripcion:
      "Identificación de peligros, evaluación y valoración de los riesgos",
    pesoPorcentual: 15,
    seccionID: "sec4",
  },
  {
    id: "des18",
    descripcion:
      "Medidas de prevención y control para intervenir los peligros/riesgos",
    pesoPorcentual: 15,
    seccionID: "sec4",
  },
  {
    id: "des19",
    descripcion: "Plan de prevención, preparación y respuesta ante emergencias",
    pesoPorcentual: 10,
    seccionID: "sec5",
  },
  {
    id: "des20",
    descripcion: "Gestión y resultados del SG-SST.",
    pesoPorcentual: 5,
    seccionID: "sec6",
  },
  {
    id: "des21",
    descripcion:
      "Acciones preventivas y correctivas con base en  los resultados del SG-SST.",
    pesoPorcentual: 10,
    seccionID: "sec7",
  },
];
