export const secciones = [
  {
    id: "sec1",
    nombre: "RECURSOS (10%)",
    calificacionSeccion: 4.0,
    ciclo: 1,
  },
  {
    id: "sec2",
    nombre:
      "GESTIÓN INTEGRAL DEL SISTEMA DE GESTIÓN DE LA SEGURIDAD Y SALUD EN EL TRABAJO (15%)",
    calificacionSeccion: 15.0,
    ciclo: 1,
  },
  {
    id: "sec3",
    nombre: "GESTIÓN DE LA SALUD (20%)",
    calificacionSeccion: 8.0,
    ciclo: 2,
  },
  {
    id: "sec4",
    nombre: "GESTIÓN DE PELIGROS Y RIESGOS (30%)",
    calificacionSeccion: 11.0,
    ciclo: 2,
  },
  {
    id: "sec5",
    nombre: "GESTIÓN DE AMENAZAS (10%)",
    calificacionSeccion: 10.0,
    ciclo: 2,
  },
  {
    id: "sec6",
    nombre: "VERIFICACIÓN DEL SG-SST (5%)",
    calificacionSeccion: 2.5,
    ciclo: 3,
  },
  {
    id: "sec7",
    nombre: "MEJORAMIENTO (10%)",
    calificacionSeccion: 7.5,
    ciclo: 4,
  },
];
